import type { Metadata } from 'next';
import { Inter } from 'next/font/google'
import './globals.css';
import '@coinbase/onchainkit/styles.css';
import '@rainbow-me/rainbowkit/styles.css';
import dynamic from 'next/dynamic';
import OnchainProviders from '@/components/wallet/OnchainProviders';

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
};

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Wagmi',
  description: 'Generated by create-wagmi',
}

export default function RootLayout(props: { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body style={{
        background: "linear-gradient(180deg, #FAFAFA 0%, #E0E3F9 100%)",
        backgroundRepeat: "no-repeat",
      }} className={`${inter.className}`}>
        <OnchainProviders>{props.children}</OnchainProviders>
      </body>
    </html>
  )
}
